server:
  port: 70301

newrelic:
  appname: dispatcherd.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

notifier:
  queues:
    access_campaign: access_campaign
    new_subscription: new_subscription
  rabbit:
    url: http://RBMQ.Url
    chan_gap: 1000000

subscriptions:
  error_redirect_url: http://id.slypee.com
  static_path: /var/www/xmp.linkit360.ru/web/
  campaign_hash_length: 32

content_client:
  dsn: localhost:70401
  timeout: 10

operator:
  db:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name:
    user:
    pass:
    port:
    host:
    table_prefix: xmp_

  private_networks:
  - start: 10.0.0.0
    end: 10.255.255.255
  - start: 100.64.0.0
    end: 100.127.255.255
  - start: 172.16.0.0
    end: 172.31.255.255
  - start: 192.0.0.0
    end: 192.0.0.255
  - start: 192.168.0.0
    end: 192.168.255.255
  - start: 198.18.0.0
    end: 198.19.255.255