server:
  port: 50300
  static_path: /var/www/xmp.linkit360.ru/web/

newrelic:
  appname: dev.dispatcherd.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

notifier:
  queues:
    access_campaign: access_campaign
    new_subscription: new_subscription
  rabbit:
    url: amqp://linkit:dg-U_oHhy7-@52.66.23.201:5672
    chan_gap: 1000000

subscriptions:
  error_redirect_url: http://id.slypee.com
  campaign_hash_length: 32

content_client:
  dsn: localhost:50301
  timeout: 10

db:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name: linkit_dev
    user: linkit
    pass: E0kZN8pUAs63wePepf
    port: 5432
    host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
    ssl_mode: disable
    table_prefix: xmp_

operator:
  private_networks:
  - start: 10.0.0.0
    end: 10.255.255.255
  - start: 100.64.0.0
    end: 100.127.255.255
  - start: 172.16.0.0
    end: 172.31.255.255
  - start: 192.0.0.0
    end: 192.0.0.255
  - start: 192.168.0.0
    end: 192.168.255.255
  - start: 198.18.0.0
    end: 198.19.255.255