server:
  port: 70301
  queue: new_subscription

newrelic:
  appname: dispatcherd
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

subscriptions:
  error_redirect_url: http://id.slypee.com
  static_path: /var/www/xmp.linkit360.ru/web/
  campaign_hash_length: 32
