server:
  port: 70301
  queue: new_subscription

newrelic:
  appname: dispatcherd.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

rabbit:
  url: http://RBMQ.Url
  chan_gap: 1000000

subscriptions:
  error_redirect_url: http://id.slypee.com
  static_path: /var/www/xmp.linkit360.ru/web/
  campaign_hash_length: 32

content_client:
  dsn:
  timeout: 10